### ISSUE TITLE
GET_USER_BY_EMAIL SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Rashmi-278** [pbteja1998/nextjs-starter#5]
Hello , I was using faunaDb for email and password auth
and I get this error after submiting the email

**Comment by Rashmi-278** [comment]
```
[next-auth][warn][nextauth_url] 
https://next-auth.js.org/warnings#nextauth_url NEXTAUTH_URL environment variable not set
GET_USER_BY_EMAIL SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.parseJSON (/home/torch/Desktop/auth/nextjs-starter/node_modules/faunadb/src/_json.js:16:15)
    at /home/torch/Desktop/auth/nextjs-starter/node_modules/faunadb/src/Client.js:264:35
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getUserByEmail (webpack-internal:///./src/adapters/fauna/index.ts:86:22)
(node:48948) UnhandledPromiseRejectionWarning: Error: GET_USER_BY_EMAIL
    at getUserByEmail (webpack-internal:///./src/adapters/fauna/index.ts:96:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:48948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:48948) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by pbteja1998** [comment]
Can you post your  `[...nextauth].js` file? I will try it from my end and see if I get the same error.

**Comment by Rashmi-278** [comment]
Actually the [...nextauth].js file was the same . I had just added the env variables for SMTP ( I was using sendinblue) and add oauth credentials. 

Will post the file and repo that I'm working on in the morning as soon I get back to working on it.  :)

**Comment by Rashmi-278** [comment]
https://github.com/Rashmi-278/nextjs-starter/tree/master
Here's the repo Im working 

Steps to reproduce the issue , 

> Initialise env variables for SMTP
> 
> npm run dev
> 
> Login with email 
> 
> console log error

```
[next-auth][warn][nextauth_url] 
https://next-auth.js.org/warnings#nextauth_url NEXTAUTH_URL environment variable not set
GET_USER_BY_EMAIL SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.parseJSON (/home/torch/Desktop/auth/nextjs-starter/node_modules/faunadb/src/_json.js:16:15)
    at /home/torch/Desktop/auth/nextjs-starter/node_modules/faunadb/src/Client.js:264:35
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getUserByEmail (webpack-internal:///./src/adapters/fauna/index.ts:86:22)
(node:10489) UnhandledPromiseRejectionWarning: Error: GET_USER_BY_EMAIL
    at getUserByEmail (webpack-internal:///./src/adapters/fauna/index.ts:96:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10489) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10489) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pbteja1998** [comment]
@Rashmi-278 are u using fauna docker container (or) are you directly using the fauna cloud secret key?

**Comment by pbteja1998** [comment]
In your fork, it seems like you changed the Fauna port to 3000, but when you run the Fauna docker container, the Fauna port is at `8443`. Revert that change, and then try.

**Comment by Rashmi-278** [comment]
Hey , yes I was using faunadb secret key and not the docker container.

I had changed it to 3000 because the oauth callback links where
unresponsive , they were listening to port 3000 And not 8443

**Comment by pbteja1998** [comment]
But that port is not the port of the next js app, it's the fauna's port. Since you are directly using the fauna DB cloud secret key, change the fauna client initialization to the following.

```js
const faunaClient = new faunadb.Client({
  secret: process.env.FAUNADB_SECRET
})
```

**Comment by Rashmi-278** [comment]
I tried it , it works , but there seems to be an issue with verification of users email. 
it works with Oauth clients google and facebook
but for email it throws this error 
```

[next-auth][warn][nextauth_url] 
https://next-auth.js.org/warnings#nextauth_url NEXTAUTH_URL environment variable not set
GET_VERIFICATION_REQUEST_ERROR TypeError: Cannot destructure property 'ref' of '(intermediate value)' as it is null.
    at getVerificationRequest (webpack-internal:///./src/adapters/fauna/index.ts:377:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[next-auth][error][callback_email_error] 
https://next-auth.js.org/errors#callback_email_error Error: GET_VERIFICATION_REQUEST_ERROR
    at getVerificationRequest (webpack-internal:///./src/adapters/fauna/index.ts:391:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

a document in verification requests collections in faunadb is created though. but when I click on the signin button in my email , I encounter this error

**Comment by pbteja1998** [comment]
Is this in the same repo that you shared earlier?

**Comment by Rashmi-278** [comment]
yes yes , I committed my changes. :)

**Comment by Rashmi-278** [comment]
yes yes , it is , Sorry for the ate reply !

**Comment by Rashmi-278** [comment]
Hey , is there a way we can resolve this ?

**Comment by pbteja1998** [comment]
How are you setting up the collections and indexes?

**Comment by Rashmi-278** [comment]
https://ibb.co/7gh6PzL

This is the setup

**Comment by pbteja1998** [comment]
Please message me on Discord. My handle is `Bhanu Teja#4468`. It is becoming difficult to resolve it with async communication on GitHub.
